spring:
  application:
    name: Learning Log
  profiles:
    group:
      default:
        active: dev
        include: dev,test,prod
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/learning_log
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  thymeleaf:
    cache: off
