spring:
  application:
    name: Learning Log
  profiles:
    group:
      default:
        active: dev
        include: dev,test,prod
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/mynotes
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  session:
    timeout: 14d

logging:
  level:
    web: debug
    org.springframework.web: debug
    org.springframework.security: debug
    jakarta.persistence: debug
    jakarta.validation: debug
    sql: debug
    root: debug
