spring:
  application:
    name: Learning Log
  profiles:
    group:
      default:
        active: dev
        include: dev,test,prod
    active: dev
  datasource:
    name: learning_log
    url: jdbc:postgresql://localhost:5432/learning_log
    username: hangalito
    password: jds.reina
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  thymeleaf:
    cache: off
logging:
  level:
    root: info
