spring:
  application:
    name: Learning Log
  profiles:
    group:
      default:
        active: dev
        include: dev,test,prod
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/learning_log
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
  session:
    timeout: 14d
